### ISSUE TITLE
On simulator/emulator works, but on device - crash

### ISSUE THREAD

**Issue by bnikollov** [fferegrino/xocr#1]
Hi! I tried your sample code on emulator/simulator (Android and iOS) and it works fine. When I tried to deploy on device (iPhone 5) during build there were a deployment error something like "Can not resolve: CGSize...". However I fix this issue by setting Linker Behavior to Don't Link. Now the app is deployed to device, but when I start the app it throws exception and crashes. The exception something about the xamarin limitations for iOS. Can you help me with that issue? Thanks in advance.

**Comment by fferegrino** [comment]
Could you provide more details regarding the last exception you get thrown?

I cleaned the project recently and deployed it to both Android & iOS devices without problems.
