### ISSUE TITLE
Its working for me but not able to read specific words

### ISSUE THREAD

**Issue by Surajvbinorkar** [fferegrino/xocr#6]
I downloaded this app and run, it working fine. There are some issues in there, first it takes too much time for API response on line,
var tessResult = await _tesseractApi.SetImage(imageBytes);
second ones I get result its not proper as I consider.
Do you have any solution on this, please let me know :) 
Thanks for sharing code  :)

**Comment by fferegrino** [comment]
Sorry, I'm no longer maintaining this repo.
